[package]
name = "pliron-tensor"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/pliron-org/pliron-tensor"
categories = ["compilers"]
keywords = ["pliron", "mlir", "tensor", "compiler"]

[dependencies]
pliron = { git = "https://github.com/pliron-org/pliron.git" }
pliron-llvm = { git = "https://github.com/pliron-org/pliron.git" }
pliron-common-dialects = { git = "https://github.com/pliron-org/pliron-common-dialects.git" }
thiserror = "2"
log = { version = "0", features = ["release_max_level_warn"] }
rustc-hash = "2"

[dev-dependencies]
expect-test = "1"
env_logger = "0"
